name: Gerar APK

on:
  workflow_dispatch:
  push:
    branches: [ "principal" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Instalar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.9'

      - name: Extrair projeto
        run: unzip -o WebRadioVemComigo_Android_Projeto.zip

      - name: Compilar APK
        working-directory: WebRadioVemComigoAndroid
        run: gradle assembleDebug

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: WebRadioVemComigo-APK
          path: WebRadioVemComigoAndroid/app/build/outputs/apk/debug/app-debug.apk
